### ISSUE TITLE
Hit or Stand function - error return is missing

### ISSUE THREAD

**Issue by ModularEntree** [ModularEntree/blackjack-in-C#1]
If the error is occured, the function breaks. This can be fixed simply by adding to error message return null.

**Comment by antoineOn** [comment]
l.195
`// i am not sure, if this will work, 'cause i am not on linux. must try it later
#ifdef __linux__ //outdated
localization local() {
    if (setlocale(LC_ALL, "") == null) {
        fprintf(stderr, "Error in locale detection.");
        return; // maybe add a standart 'localization' struct object initialized at a null value in order to return it
    }if (!strcmp(setlocale(LC_ALL, ""), setlocale(LC_ALL, "cs_CZ.UTF-8"))) {
        // Czech localization (cause i am czech, lol)`

Here is what i would do :)

**Comment by ModularEntree** [comment]
Thanks a lot!
